name: remote ssh and deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd /home/ubuntu/squid-game;
          git pull origin master;
          ddusi
          ${{ secrets.USER_TOKEN }}
          yarn build;
          pm2 restart all; 
      
#     - name: Discord Alert Success
#       uses: sarisia/actions-status-discord@v1
#       if: success()
#       with:
#         webhook: ${{ secrets.DISCORD_WEBHOOK }}
#         description: "ğŸ‰ ì‚¬ì´íŠ¸ê°€ ë°°í¬ë˜ì—ˆìŠµë‹ˆë‹¤!"

#     - name: Discord Alert Failure
#       uses: sarisia/actions-status-discord@v1
#       if: failure()
#       with:
#         webhook: ${{ secrets.DISCORD_WEBHOOK }}
#         description: "ğŸ”¥ ì‚¬ì´íŠ¸ ë°°í¬ë¥¼ ì‹¤íŒ¨í•˜ì˜€ìŠµë‹ˆë‹¤."
